# --------------------
# WEEKDAY
# --------------------

- alias: Bed room lights on if there is motion on a weekday
  trigger:
    platform: state
    entity_id: input_boolean.motion_bed_room
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '06:30:00'
    before: '22:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_normal

- alias: Bed room lights dimmed if there is no motion on a weekday
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:01:00'
  condition:
    condition: time
    after: '06:30:00'
    before: '22:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_dimmed
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room

- alias: Bed room lights turned off if there is no motion on a weekday
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:06:00'
  condition:
    condition: time
    after: '06:30:00'
    before: '22:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room

- alias: Bed room lights on if there is motion on a weekday night
  trigger:
    platform: state
    entity_id: input_boolean.motion_bed_room
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '22:00:00'
    before: '22:40:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_night

- alias: Bed room lights turned off if there is no motion on a weekday night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:00:30'
  condition:
    condition: time
    after: '22:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room

# ----------------------
# WEEKEND
# ----------------------

- alias: Bed room lights on if there is motion in a weekend
  trigger:
    platform: state
    entity_id: input_boolean.motion_bed_room
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
    weekday:
      - sat
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_normal


- alias: Bed room lights dimmed if there is no motion in a weekend
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:01:00'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
    weekday:
      - sat
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_dimmed
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room

- alias: Bed room lights turned off if there is no motion on a weekend day
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:06:00'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
    weekday:
      - sat
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room

- alias: Bed room lights dimmed if there is motion on a weekend night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    above: 2
  condition:
    condition: time
    after: '22:00:00'
    weekday:
      - fri
      - sat  
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_night
 
- alias: Bed room lights dimmed if there is motion on a weekend night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    above: 2
  condition:
    condition: time
    before: '01:30:00'
    weekday:
      - sat
      - sun
  action:
    service: scene.turn_on
    entity_id: scene.Bed_room_night

- alias: Bed room lights off, no motion, 00-0130
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:00:30'
  condition:
    condition: time
    before: '01:30:00'
    weekday:
      - sat
      - sun
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room


- alias: Bed room lights off, no motion 22-00
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
    below: 2
    for: '00:00:30'
  condition:
    condition: time
    after: '22:00:00'
    weekday:
      - fri
      - sat
  action:
    - service: scene.turn_on
      entity_id: scene.Bed_room_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_bed_room
