# CHANGE STATES OF MOTION BOOLEANS WHEN SENSORS DETECTS MOTION

# LIVING ROOM
  - alias: Living room motion boolean ON when motion detected
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_living_room_burglar
      above: 3
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.motion_living_room

#- alias: Living room motion boolean OFF when no motion detected
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
#    below: 4
#    for: '00:01:00'
#  action:
#    - service: input_boolean.turn_off
#      entity_id: input_boolean.motion_living_room

# GUEST ROOM
  - alias: Guest room motion boolean ON when motion detected
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_guest_room_burglar
      above: 3
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.motion_guest_room

  - alias: Guest room reading light boolean on when reading light turns on
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_smart_dimmer_6_guest_room_power
      above: 1
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_room_reading_light_state

  - alias: Guest room reading light boolean off when reading light turns off
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_smart_dimmer_6_guest_room_power
      below: 1
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_room_reading_light_state

#  - alias: Guest room motion boolean OFF when no motion detected
#    trigger:
#      platform: numeric_state
#      entity_id: sensor.aeotec_multisensor_6_guest_room_burglar
#      below: 4
#      for: '00:01:00'
#    action:
#      - service: input_boolean.turn_off
#        entity_id: input_boolean.motion_guest_room

# HALL WAY
  - alias: Hall way motion boolean ON when motion detected
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_hall_way_burglar
      above: 2
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.motion_hall_way
      - delay: '00:00:02'
      - service: input_boolean.turn_off
        entity_id: input_boolean.motion_hall_way


#- alias: Hall way motion boolean OFF when no motion
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.aeotec_multisensor_6_hall_way_burglar
#    below: 4
#    for: '00:01:00'
#  action:
#    - service: input_boolean.turn_off
#      entity_id: input_boolean.motion_hall_way

# BED ROOM
  - alias: Bed room motion boolean ON when motion detected
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
      above: 3
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.motion_bed_room

  - alias: Bed room motion boolean OFF when no motion detected
    trigger:
      platform: numeric_state
      entity_id: sensor.aeotec_multisensor_6_bed_room_burglar
      below: 4
      for: '00:01:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.motion_bed_room
