#########################################################
#							                                          #
#                        TIMERS                         #  
#						                                           	#
#########################################################

# The following timers start when movement is detected in the living room.
# The length of the timers depend on the time they are activated.
# The timer lengths are found by live testing in an "operational" environment.


# Living room timer start, morning

- alias: Living room timer, morning
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 2
  condition:
    condition: time
    after: '06:00'
    before: '08:30'
  action:
    - service: timer.start
      data:
        entity_id: timer.timer_living_room
        duration: '00:15:00'
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "Hjem fra jobb"


# Living room timer start, daytime

- alias: Living room timer, day
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 2
  condition:
    condition: time
    after: '08:30'
    before: '23:30'
  action:
    - service: timer.start
      data:
        entity_id: timer.timer_living_room
        duration: '01:10:00'

# Living room timer start, evening

- alias: Living room timer, evening
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 2
  condition:
    condition: time
    after: '23:30'
    before: '01:30'
  action:
    - service: timer.start
      data:
        entity_id: timer.timer_living_room
        duration: '00:30:00'

# Living room timer start, night

- alias: Living room timer, night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 2
  condition:
    condition: time
    after: '01:30'
    before: '06:00'
  action:
    - service: timer.start
      data:
        entity_id: timer.timer_living_room
        duration: '00:05:00'

# Living room lights off when timer runs out

- alias: Living room lights on when timer runs out
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_living_room
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_off


#########################################################
#                                                       #
#                    AUTOMATIONS                        #
#                                                       #
#########################################################


# If movement
#
#
#
#
#
#
#
#
#
#
#



 #Living room lights on when there is motion

- alias: Living room lights on when motion, daylight
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 3
  condition:
    condition: and
    conditions:
  #   - condition: state
  #     entity_id: timer.timer_living_room
  #     state: 'idle'
     - condition: numeric_state
       entity_id: sensor.aeotec_multisensor_6_living_room_luminance
       below: '140'
       above: '40'
     - condition: or
       conditions:
         - condition: state
           entity_id: 'light.ph5'
           state: 'off'
         - condition: state
           entity_id: 'light.wood'
           state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_normal_day


- alias: Living room lights on when motion, normal
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 3
  condition:
    condition: and
    conditions:
#     - condition: state
#       entity_id: timer.timer_living_room
#       state: 'idle'
     - condition: numeric_state
       entity_id: sensor.aeotec_multisensor_6_living_room_luminance
       below: '40'
     - condition: or
       conditions:
         - condition: state
           entity_id: 'light.ph5'
           state: 'off'
         - condition: state
           entity_id: 'light.wood'
           state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_normal


- alias: Living room window lights on when luminance decrease and the other lights are on
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_luminance
    below: '40'
    for: '00:00:30'
  condition:
    condition: or
    conditions:
     - condition: state
       entity_id: 'light.ph5'
       state: 'on'
     - condition: state
       entity_id: 'light.wood'
       state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_normal


# Living room lights off when sufficient ambient light

- alias: Living room lights off when sufficient ambient light
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_luminance
    above: '90'
    for: '00:01:00'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_off
    - service: timer.finished
      data:      
        entity_id: timer.timer_living_room
      

- alias: Living room window lights off when sufficient ambient light
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_luminance
    above: '40'
    for: '00:00:30'
  action:
    - service: light.turn_off
      entity_id: light.aj
      data:
        transition: 3

# Dim living room lights when no motion during the day

- alias: Living room lights dimmed, day
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '01:00:00'
  condition:
    condition: time
    after: '09:00'
    before: '23:30'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_dimmed

# Dim living room lights when no motion during the evening

- alias: Living room lights dimmed, evening
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '00:30:00'
  condition:
    condition: time
    after: '23:30'
    before: '02:00'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_dimmed

# Dim living room lights when no motion during the night

- alias: Living room lights dimmed, night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '00:04:00'
  condition:
    condition: time
    after: '02:00'
    before: '09:00'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_dimmed


# Living room lights off when no motion

- alias: Living room lights off when no motion, day
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '01:15:00'
  condition:
    condition: time
    after: '09:00'
    before: '23:30'
  action:
    - service: light.turn_off
      entity_id: light.wood
      data:
        transition: 1
    - delay: '00:00:01'
    - service: light.turn_off
      entity_id: light.aj
      data:
        transition: 1
    - delay: '00:00:01'
    - service: light.turn_off
      entity_id: light.ph5
      data:
        transition: 1
    - delay: '00:00:01'
    - service: light.turn_off
      entity_id: light.aeotec_smart_dimmer_6_living_room_level

- alias: Living room lights off when no motion, evening
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '00:45:00'
  condition:
    condition: time
    after: '23:30'
    before: '02:00'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_off

- alias: Living room lights off when no motion, night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 3
    for: '00:06:00'
  condition:
    condition: time
    after: '02:00'
    before: '09:00'
  action:
    - service: scene.turn_on
      entity_id: scene.Living_room_off
