# TV rack power on when motion in the living room

- alias: TV rack power on when motion in the living room
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    above: 3
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.everspring_an180_plugin_onoff_module_switch


# TV rack power off when no motion for a long time

- alias: TV rack power off when no motion in the living room
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 4
    for: '03:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.everspring_an180_plugin_onoff_module_switch

- alias: TV rack power off when no motion in the living room in the night
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_multisensor_6_living_room_burglar
    below: 4
    for: '01:00:00'
  condition:
    condition: time
    after: '01:00'
    before: '08:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.everspring_an180_plugin_onoff_module_switch

